// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyazjsqttydzoqddaqbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5YXpqc3F0dHlkem9xZGRhcWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDQxMTMsImV4cCI6MjA2ODYyMDExM30.t-WT-fZ3CqGmzhzZdoC-m68B1ZiVd35vlKpVxoZ97Mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});